#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 04, 2024 10:26:20 AM CEST  platform: Windows NT

import os
import sys
if not os.path.dirname(__file__) in sys.path:
    sys.path.append(os.path.dirname(__file__))
    
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import iocV7

_debug = True  # False to eliminate debug printing from callback functions.

def on_destroy():
    root.destroy()
    sys.exit()

def open_second_window(window_title, RW_csv, cali, std_cali):
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = iocV7.TW_Result(_top2, RW_csv, cali, std_cali)
    _top2.title(f"Results for: {window_title}")

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', on_destroy)
    
    # Create the first window
    global _top1, _w1
    _top1 = root
    _w1 = iocV7.Toplevel1(_top1)
    
    root.mainloop()

if __name__ == '__main__':
    iocV7.start_up()




