#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 28, 2024 11:41:46 AM CEST  platform: Windows NT

### Define file locations
import sys
import os

def dir_add(directory_name: str):
    # Adds a specific directory to the current sys path
    # Only works with directories stored in same folder as this code.
    dir_path = os.path.join(os.path.dirname(__file__), directory_name)
    if not dir_path in sys.path:
        sys.path.append(dir_path)
    
if not os.path.dirname(__file__) in sys.path:
    sys.path.append(os.path.dirname(__file__))
dir_add("Project Files")
###
    
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import filedialog, messagebox
import webbrowser
import calibrator3
import dobbel

_location = os.path.dirname(__file__)
if not os.path.dirname(__file__) in sys.path:
    sys.path.append(os.path.dirname(__file__))


if os.path.dirname(__file__) in sys.path:
    print("DIRECTORY FOLDER IS IN SYSTEM PATH!")
else:
    print(f"DIrectory folder not found in {sys.path}")

import IoC_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("871x467+293+74")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

      


        self.top = top
        self.selected_directory = ""
        self.selected_file = ""
        self.is_die_connected = None
        self.created_die = None
        
        # Variables
        
        
        
        self.Frame3 = tk.Frame(self.top)
        self.Frame3.place(relx=0.078, rely=0.099, relheight=0.146
                , relwidth=0.814)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="#000000")

        self.Message1 = tk.Message(self.Frame3)
        self.Message1.place(relx=0.206, rely=0.132, relheight=0.794
                , relwidth=0.549)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(font="-family {Segoe UI} -size 9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="#000000")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Titel''')
        self.Message1.configure(width=400)

        self.Button7 = tk.Button(self.top)
        self.Button7.place(relx=0.078, rely=0.878, height=26, width=97)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="black")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="#000000")
        self.Button7.configure(text='''Quit program''')
        self.Button7.configure(command=self.stop_kernel)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.078, rely=0.255, relheight=0.595, relwidth=0.44)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Button8 = tk.Button(self.Frame1)
        self.Button8.place(relx=0.076, rely=0.885, height=26, width=97)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="black")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(cursor="fleur")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="#000000")
        self.Button8.configure(text='''Import''')

        self.Button9 = tk.Button(self.Frame1)
        self.Button9.place(relx=0.684, rely=0.885, height=26, width=97)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="black")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="#000000")
        self.Button9.configure(text='''Apply''')
        self.Button9.configure(state=tk.DISABLED)
        self.Button9.configure(command=self.apply_selection)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.052, rely=0.047, height=19, width=72)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Symbol} -size 9")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Data folder:''')

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.052, rely=0.165, relheight=0.694
                , relwidth=0.896)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="#000000")
        self.Listbox1.configure(selectbackground="#d9d9d9")
        self.Listbox1.configure(selectforeground="black")
        self.Listbox1.bind('<<ListboxSelect>>', self.on_select)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.76, rely=0.036, height=26, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(command=self.browse_directory)
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Browse''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.235, rely=0.047, height=19, width=189)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''Select a file''')

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.525, rely=0.255, relheight=0.595
                , relwidth=0.366)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="#000000")

        self.Button5 = tk.Button(self.Frame2)
        self.Button5.place(relx=0.06, rely=0.853, height=26, width=287)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {Segoe UI} -size 9")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="#000000")
        self.Button5.configure(text='''Results''')
        self.Button5.configure(command=self.open_results_toplevel)

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.06, rely=0.755, height=19, width=73)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 9")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Loaded file:''')

        self.Button6 = tk.Button(self.Frame2)
        self.Button6.place(relx=0.06, rely=0.032, height=26, width=117)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 9")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="#000000")
        self.Button6.configure(text='''Connect''')
        self.Button6.configure(command=self.connect_die)

        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.06, rely=0.165, height=26, width=117)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(text='''Calibrate''')
        self.Button2.configure(command=self.calibrate)

        self.Label4 = tk.Label(self.Frame2)
        self.Label4.place(relx=0.304, rely=0.755, height=19, width=198)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="#000000")
        self.Label4.configure(text='''Label''')

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.063, rely=0.36, height=21, width=84)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(compound='center')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label6.configure(foreground="#ff0000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="#000000")
        self.Label6.configure(text='''Not Calibrated''')

        self.Label5 = tk.Label(self.Frame2)
        self.Label5.place(relx=0.063, rely=0.288, height=21, width=103)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="#000000")
        self.Label5.configure(text='''Status Calibration:''')

        self.Button3 = tk.Button(self.Frame2)
        self.Button3.place(relx=0.58, rely=0.032, height=26, width=117)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''Guide''')
        self.Button3.configure(command=self.open_website)

        self.Button4 = tk.Button(self.Frame2)
        self.Button4.place(relx=0.58, rely=0.165, height=26, width=117)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(cursor="fleur")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 9")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="#000000")
        self.Button4.configure(state='disabled')
        self.Button4.configure(text='''Start Logging''')
        
        top.protocol("WM_DELETE_WINDOW", self.stop_kernel)
        
    def stop_kernel(self):
        self.top.destroy()
        sys.exit()
        
    def browse_directory(self):
        self.selected_directory = filedialog.askdirectory()
        if self.selected_directory:
            self.Label3.configure(text=self.selected_directory)
            self.Listbox1.delete(0, tk.END)
            for filename in os.listdir(self.selected_directory):
                if filename.endswith('.csv'):
                    self.Listbox1.insert(tk.END, filename)
                
    def on_select(self, event):
        selected_item = self.Listbox1.curselection()
        if selected_item:
            self.Button9.configure(state=tk.NORMAL)
            
    def apply_selection(self):
        selected_item = self.Listbox1.curselection()
        if selected_item:
            selected_file_name = self.Listbox1.get(selected_item)
            self.selected_file = os.path.join(self.selected_directory, selected_file_name)
            self.Label4.configure(text=selected_file_name)
            
    def open_website(self):
        webbrowser.open("https://github.com/jrspan/dobbelsteenbep")
    
    def connect_die(self):
        self.created_die = dobbel.dobbellogger()
        
    def open_results_toplevel(self):
        # Create and show the new Toplevel window
        results_top = tk.Toplevel(self.top)
        Toplevel2(results_top)
        
    def calibrate(self):
        calibrator3.calibrate()

            
class Toplevel2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("999x450+267+203")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 1")
        top.configure(background="#efebe7")
        top.configure(highlightbackground="#efebe7")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame7 = tk.Frame(self.top)
        self.Frame7.place(relx=0.586, rely=0.131, relheight=0.329
                , relwidth=0.268)
        self.Frame7.configure(relief='groove')
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#efebe7")
        self.Frame7.configure(highlightbackground="#efebe7")
        self.Frame7.configure(highlightcolor="black")

        self.Frame6 = tk.Frame(self.top)
        self.Frame6.place(relx=0.306, rely=0.593, relheight=0.327
                , relwidth=0.254)
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief="groove")
        self.Frame6.configure(background="#efebe7")
        self.Frame6.configure(highlightbackground="#efebe7")
        self.Frame6.configure(highlightcolor="black")

        self.Frame8 = tk.Frame(self.top)
        self.Frame8.place(relx=0.586, rely=0.593, relheight=0.329
                , relwidth=0.268)
        self.Frame8.configure(relief='groove')
        self.Frame8.configure(borderwidth="2")
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#efebe7")
        self.Frame8.configure(highlightbackground="#efebe7")
        self.Frame8.configure(highlightcolor="black")

        self.Frame4 = tk.Frame(self.top)
        self.Frame4.place(relx=0.05, rely=0.131, relheight=0.789, relwidth=0.238)

        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#efebe7")
        self.Frame4.configure(highlightbackground="#efebe7")
        self.Frame4.configure(highlightcolor="black")

        self.Label10 = tk.Label(self.Frame4)
        self.Label10.place(relx=0.055, rely=0.141, height=21, width=77)
        self.Label10.configure(activebackground="#d9d9d9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(anchor='w')
        self.Label10.configure(background="#efebe7")
        self.Label10.configure(compound='left')
        self.Label10.configure(disabledforeground="#b3b0ad")
        self.Label10.configure(foreground="black")
        self.Label10.configure(highlightbackground="#efebe7")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Total time of throw:''')

        self.Label7 = tk.Label(self.Frame4)
        self.Label7.place(relx=0.055, rely=0.225, height=21, width=90)
        self.Label7.configure(activebackground="#d9d9d9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#efebe7")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#b3b0ad")
        self.Label7.configure(foreground="black")
        self.Label7.configure(highlightbackground="#efebe7")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Maximum acceleration:''')

        self.Label7_1 = tk.Label(self.Frame4)
        self.Label7_1.place(relx=0.055, rely=0.31, height=21, width=104)
        self.Label7_1.configure(activebackground="#d9d9d9")
        self.Label7_1.configure(activeforeground="black")
        self.Label7_1.configure(anchor='w')
        self.Label7_1.configure(background="#efebe7")
        self.Label7_1.configure(compound='left')
        self.Label7_1.configure(disabledforeground="#b3b0ad")
        self.Label7_1.configure(font="-family {Segoe UI} -size 9")
        self.Label7_1.configure(foreground="black")
        self.Label7_1.configure(highlightbackground="#efebe7")
        self.Label7_1.configure(highlightcolor="black")
        self.Label7_1.configure(text='''Maximum angular velocity:''')

        self.Label9 = tk.Label(self.Frame4)
        self.Label9.place(relx=0.055, rely=0.366, height=41, width=77)
        self.Label9.configure(activebackground="#d9d9d9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(anchor='w')
        self.Label9.configure(background="#efebe7")
        self.Label9.configure(compound='left')
        self.Label9.configure(disabledforeground="#b3b0ad")
        self.Label9.configure(foreground="black")
        self.Label9.configure(highlightbackground="#efebe7")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Traveled distance:''')

        self.Label8 = tk.Label(self.Frame4)
        self.Label8.place(relx=0.055, rely=0.479, height=21, width=90)
        self.Label8.configure(activebackground="#d9d9d9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#efebe7")
        self.Label8.configure(compound='left')
        self.Label8.configure(disabledforeground="#b3b0ad")
        self.Label8.configure(foreground="black")
        self.Label8.configure(highlightbackground="#efebe7")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Number on top:''')

        self.Label11 = tk.Label(self.Frame4)
        self.Label11.place(relx=0.055, rely=0.056, height=21, width=50)
        self.Label11.configure(activebackground="#d9d9d9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(anchor='w')
        self.Label11.configure(background="#efebe7")
        self.Label11.configure(compound='left')
        self.Label11.configure(disabledforeground="#b3b0ad")
        self.Label11.configure(foreground="black")
        self.Label11.configure(highlightbackground="#efebe7")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Data file:''')

        self.Label16 = tk.Label(self.Frame4)
        self.Label16.place(relx=0.508, rely=0.31, height=21, width=23)
        self.Label16.configure(activebackground="#d9d9d9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(anchor='w')
        self.Label16.configure(background="#efebe7")
        self.Label16.configure(compound='left')
        self.Label16.configure(disabledforeground="#b3b0ad")
        self.Label16.configure(foreground="black")
        self.Label16.configure(highlightbackground="#efebe7")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''Label''')

        self.Label17 = tk.Label(self.Frame4)
        self.Label17.place(relx=0.508, rely=0.394, height=21, width=23)
        self.Label17.configure(activebackground="#d9d9d9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(anchor='w')
        self.Label17.configure(background="#efebe7")
        self.Label17.configure(compound='left')
        self.Label17.configure(disabledforeground="#b3b0ad")
        self.Label17.configure(foreground="black")
        self.Label17.configure(highlightbackground="#efebe7")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''Label''')

        self.Label18 = tk.Label(self.Frame4)
        self.Label18.place(relx=0.508, rely=0.479, height=21, width=23)
        self.Label18.configure(activebackground="#d9d9d9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(anchor='w')
        self.Label18.configure(background="#efebe7")
        self.Label18.configure(compound='left')
        self.Label18.configure(disabledforeground="#b3b0ad")
        self.Label18.configure(foreground="black")
        self.Label18.configure(highlightbackground="#efebe7")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''Label''')

        self.Label13 = tk.Label(self.Frame4)
        self.Label13.place(relx=0.508, rely=0.056, height=21, width=23)
        self.Label13.configure(activebackground="#d9d9d9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(anchor='w')
        self.Label13.configure(background="#efebe7")
        self.Label13.configure(compound='left')
        self.Label13.configure(disabledforeground="#b3b0ad")
        self.Label13.configure(foreground="black")
        self.Label13.configure(highlightbackground="#efebe7")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''Label''')

        self.Label14 = tk.Label(self.Frame4)
        self.Label14.place(relx=0.508, rely=0.141, height=21, width=23)
        self.Label14.configure(activebackground="#d9d9d9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(anchor='w')
        self.Label14.configure(background="#efebe7")
        self.Label14.configure(compound='left')
        self.Label14.configure(disabledforeground="#b3b0ad")
        self.Label14.configure(foreground="black")
        self.Label14.configure(highlightbackground="#efebe7")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''Label''')

        self.Label15 = tk.Label(self.Frame4)
        self.Label15.place(relx=0.508, rely=0.225, height=21, width=23)
        self.Label15.configure(activebackground="#d9d9d9")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(anchor='w')
        self.Label15.configure(background="#efebe7")
        self.Label15.configure(compound='left')
        self.Label15.configure(disabledforeground="#b3b0ad")
        self.Label15.configure(foreground="black")
        self.Label15.configure(highlightbackground="#efebe7")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''Label''')

        self.Frame5 = tk.Frame(self.top)
        self.Frame5.place(relx=0.306, rely=0.131, relheight=0.324
                , relwidth=0.253)
        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief="groove")
        self.Frame5.configure(background="#efebe7")
        self.Frame5.configure(highlightbackground="#efebe7")
        self.Frame5.configure(highlightcolor="black")
        
    def stop_kernel(self):
        self.top.destroy()
        sys.exit()

def start_up():
    IoC_support.main()

if __name__ == '__main__':
    IoC_support.main()




