#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 28, 2024 10:27:36 AM CEST  platform: Windows NT
#    May 28, 2024 10:57:57 AM CEST  platform: Windows NT
#    May 28, 2024 11:41:53 AM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os

if not os.path.dirname(__file__) in sys.path:
    sys.path.append(os.path.dirname(__file__))


import IoC

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = IoC.Toplevel1(_top1)
    
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = IoC.Toplevel2(_top2)
    
    root.mainloop()

if __name__ == '__main__':
    IoC.start_up()





